version: '3.8'

services:
  app:
    image: unjam-frontend:latest
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - .env.production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
