# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      APP_NAME: unjam-frontend
      DOMAIN: unjam.nickreffitt.com
      LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      STRIPE_TABLE_ID: ${{ secrets.STRIPE_TABLE_ID }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Install Deno for edge functions
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Run unit tests
      - name: Run unit tests
        run: npm test

      # Run Cypress tests using the official GitHub Action
#      - name: Cypress run
#        uses: cypress-io/github-action@v6
#        env:
#          NODE_ENV: 'development'
#          VITE_USE_LOCAL_AUTH: 'true'
#        with:
#          start: npm run dev:edge, npm run dev:unified
#          wait-on: 'http://localhost:5175'
#          wait-on-timeout: 120
#          browser: chrome
#          command: npm run cypress:run

      # Upload Cypress screenshots on failure
#      - name: Upload Cypress screenshots
#        uses: actions/upload-artifact@v4
#        if: failure()
#        with:
#          name: cypress-screenshots
#          path: cypress/screenshots/
#          if-no-files-found: ignore

      - name: Build and upload extension to Supabase
        run: |
          # Build the extension
          npm run build:ext
          npm run zip:ext

          # Find the generated zip file
          ZIP_FILE=$(find .output -name "*.zip" -type f | head -n 1)

          if [ -z "$ZIP_FILE" ]; then
            echo "Error: No zip file found in .output directory"
            exit 1
          fi

          echo "Found extension zip: $ZIP_FILE"

          # Extract filename from path
          FILENAME=$(basename "$ZIP_FILE")
          echo "FILENAME=$FILENAME"

          # Set environment variable for subsequent steps
          echo "EXTENSION_ZIP_FILENAME=${FILENAME}" >> $GITHUB_ENV
          echo "ZIP_FILE=${ZIP_FILE}" >> $GITHUB_ENV

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link Supabase project
        run: supabase link --project-ref ${{ env.PROJECT_ID }}
      - name: Upload zip file
        run: supabase storage cp "${{ env.ZIP_FILE }}" "extensions/${{ env.EXTENSION_ZIP_FILENAME }}" --experimental

      - name: Build Docker image locally
        run: |
          docker build -f ./deploy/Dockerfile \
            --build-arg EXTENSION_ZIP_FILENAME=${{ env.EXTENSION_ZIP_FILENAME }} \
            -t ${{ env.APP_NAME }}:latest .
          docker save ${{ env.APP_NAME }}:latest -o /tmp/image.tar
          ls -la /tmp/image.tar

      - name: Transfer Docker image to server
        run: |
          echo "${{ secrets.SVR_PRIVATE_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no /tmp/image.tar ${{ secrets.SVR_USERNAME }}@${{ secrets.SVR_HOST }}:/tmp/
          rm /tmp/ssh_key

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SVR_HOST }}
          username: ${{ secrets.SVR_USERNAME }}
          key: ${{ secrets.SVR_PRIVATE_KEY }}
          envs: APP_NAME,DOMAIN,LETSENCRYPT_EMAIL,SUPABASE_URL,SUPABASE_ANON_KEY,STRIPE_TABLE_ID,STRIPE_PUBLISHABLE_KEY,EXTENSION_ZIP_FILENAME
          script: |
            # Update system packages
            apt update

            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
              apt update
              apt install -y docker-ce docker-ce-cli containerd.io
              systemctl start docker
              systemctl enable docker
              echo "Docker installed successfully"
            else
              echo "Docker already installed"
            fi

            # Install Nginx if not installed
            if ! command -v nginx &> /dev/null; then
              echo "Installing Nginx..."
              apt install -y nginx
              systemctl start nginx
              systemctl enable nginx
              echo "Nginx installed successfully"
            else
              echo "Nginx already installed"
            fi

            # Install Certbot if not installed
            if ! command -v certbot &> /dev/null; then
              echo "Installing Certbot..."
              apt install -y certbot python3-certbot-nginx
              echo "Certbot installed successfully"
            else
              echo "Certbot already installed"
            fi

            # Load Docker image from tar file
            docker load -i "/tmp/image.tar"

            # Stop and remove existing container
            docker stop "$APP_NAME" || true
            docker rm "$APP_NAME" || true

            # Create .env.production file for the container
            echo "VITE_SUPABASE_URL=$SUPABASE_URL" > /tmp/.env.production
            echo "VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> /tmp/.env.production
            echo "VITE_STRIPE_TABLE_ID=$STRIPE_TABLE_ID" >> /tmp/.env.production
            echo "VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY" >> /tmp/.env.production
            echo "VITE_EXTENSION_ZIP_FILENAME=$EXTENSION_ZIP_FILENAME" >> /tmp/.env.production

            # Run the new container
            docker run -d --name "$APP_NAME" --restart unless-stopped -p 3000:80 \
              --env-file /tmp/.env.production \
              "$APP_NAME:latest"

            # Clean up any broken nginx symlinks
            find /etc/nginx/sites-enabled -type l -exec test ! -e {} \; -delete

            # Set up nginx configuration if it doesn't exist
            if [ ! -f "/etc/nginx/sites-available/$DOMAIN" ]; then
              tee "/etc/nginx/sites-available/$DOMAIN" > /dev/null <<EOF
            server {
                listen 80;
                server_name $DOMAIN;

                location / {
                    proxy_pass http://localhost:3000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }
            EOF

              # Enable the site
              ln -sf "/etc/nginx/sites-available/$DOMAIN" /etc/nginx/sites-enabled/
              nginx -t && systemctl reload nginx

              # Get SSL certificate
              certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$LETSENCRYPT_EMAIL"
            fi

            # Clean up transferred tar file and old images
            rm -f "/tmp/image.tar"
            docker image prune -f