# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Build the app in dev mode
      - name: Build app (dev)
        run: npm run build

      # Run unit tests
      - name: Run unit tests
        run: npm test

  # Functional test job with Cypress
  functional-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Start unified dev server in background
      - name: Start unified dev server
        run: npm run dev:unified &

      # Wait for server to be ready
      - name: Wait for server to start
        run: |
          echo "Waiting for server to be ready..."
          npx wait-on http://localhost:5173 --timeout 60000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run
